[project]
authors = ["Hasem Mallick <hasemmallick19@students.cutn.ac.in>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "django_curd"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
django = ">=5.1.2,<6"
psycopg2 = ">=2.9.9,<3"
psycopg2-binary = ">=2.9.9,<3"
gdal = ">=3.9.2,<4"
djangorestframework-gis = ">=1.1,<2"
djangorestframework = ">=3.15.2,<4"
markdown = ">=3.6,<4"
django-filter = ">=24.3,<25"
django-cors-headers = ">=4.4.0,<5"
