# Generated by Django 5.1.2 on 2024-10-10 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='continent',
            table='continents123',
        ),
        migrations.AlterModelTable(
            name='country',
            table='countries123',
        ),
    ]
