# Generated by Django 5.1.2 on 2024-10-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_us_cities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='US_cities',
        ),
    ]
