# Generated by Django 5.1.2 on 2024-10-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_delete_us_cities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.RenameField(
            model_name='continent',
            old_name='name',
            new_name='gid',
        ),
        migrations.RemoveField(
            model_name='continent',
            name='code',
        ),
        migrations.AlterModelTable(
            name='continent',
            table='continents',
        ),
    ]
