# Generated by Django 5.1.2 on 2024-10-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_delete_country_rename_name_continent_gid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='USCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Continent',
        ),
    ]
