# Generated by Django 5.1.2 on 2024-10-10 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_uscity_delete_continent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uscity',
            options={'managed': False},
        ),
    ]
