# Generated by Django 5.1.2 on 2024-10-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_alter_uscity_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uscity',
            table='us_cities',
        ),
    ]
