# Generated by Django 5.1.2 on 2024-10-10 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_roadnetwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='USCity',
        ),
    ]
