# Generated by Django 5.1.2 on 2024-10-10 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_delete_uscity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roadnetwork',
            table='kandra_road_network',
        ),
    ]
