# Generated by Django 5.1.2 on 2024-10-10 15:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_alter_roadnetwork_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='NYCStreets',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
            options={
                'db_table': 'nyc_streets',
                'managed': False,
            },
        ),
    ]
