# Generated by Django 5.1.2 on 2024-10-10 15:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_nycstreets'),
    ]

    operations = [
        migrations.CreateModel(
            name='NYCNeighborhoods',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'db_table': 'nyc_neighborhoods',
                'managed': False,
            },
        ),
    ]
