# Generated by Django 5.1.2 on 2025-02-13 03:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_nycneighborhoods'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoJSONData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('description', models.TextField()),
            ],
        ),
    ]
