# Generated by Django 5.1.2 on 2025-02-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='entity',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
