# Generated by Django 5.1.2 on 2025-02-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_entity_latitude_entity_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterModelTable(
            name='entity',
            table='webapp_entity',
        ),
    ]
