# Generated by Django 5.1.2 on 2025-02-13 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0017_alter_entity_latitude_alter_entity_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='latitude',
            field=models.FloatField(default=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterModelTable(
            name='entity',
            table=None,
        ),
    ]
