# Generated by Django 5.1.2 on 2025-02-13 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_alter_entity_latitude_alter_entity_longitude_and_more'),
    ]

    operations = [
    ]
